# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Skateboarding: /skateboarding
  # SKateboard: /categories/skateboard
  # About: /about
  About: https://jingwang.site
rss: /atom.xml

since: 2019

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico or avatar.jpg into `hexo-site/themes/hiker/source/` directory.
avatar:
  enable: true
  border: true
  width: 124
  height: 124
  top: 0
  url: css/images/mylogo.jpg


# Homepage
# eg. home_background_image: [css/images/home-bg.jpg, http://t.cn/RMbvEza]
# eg. mode: image | polyline | trianglify
home_background_image:
  enable: true
  mode: image
  rolling: true
  url: [css/images/moon.jpg]

# css/images/fyenman.jpg, css/images/home2.jpg, css/images/home3.jpg https://source.unsplash.com/collection/954550/1920x1080

home_logo_image:
  enable: false
  border: true
  url: css/images/homelogo.jpg


# AboutPage background
# about_big_image: [css/images/pose.jpg]
about_big_image: []



# Archive pagination
archive_pagination: true


# Post Article's Content
post_catalog:
  enable: true
# 开启主页摘要
post_excerpt: true


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
# - social
- tagcloud
- category
# - tag
- archive
# - recent_posts


# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Email: JingwangLi@foxmail.com
  Github: https://github.com/JingwangLi
  Zhihu: https://www.zhihu.com/people/JingwangLi
  Douban: https://www.douban.com/people/iLJW/
  # Twitter: https://twitter.com/JingwangLi
  # Facebook: https://www.facebook.com/jingwang1997
  # Instagram: https://www.instagram.com/jingwang.li
  # Weibo: https://weibo.com/JingwangLi
  # Google-plus:
  # Pinterest:
  # Flickr:


# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname:
# livere_shortname: MTAyMC8yOTQ4MS82MDQ5 #原作者
# livere_shortname: MTAyMC8yODg1NC81NDI0 #某博客作者
# livere_shortname: MTAyMC80NzkzOC8yNDQzNQ== #foxmail
# livere_shortname: MTAyMC80MjgyMC8xOTM2Nw== #gmail
# livere_shortname: MTAyMC80MjgyMS8xOTM2OA #qq 已注销
# livere_shortname: MTAyMC8zMzMwNC85ODYx #original
uyan_uid:
wumii:

valine:
  enable: true
  app_id: aToRWTvLvg1HEDjFRlAg7evB-gzGzoHsz
  app_key: Tp0GfA13PbrlgRPNUEU2XJ8H
  notify: false   #邮件提醒设置
  verify: false   #验证码设置
  placeholder: If you have any problems, please let me know. You'd better leave your email address at the top to get notification when I reply.
  avatar: retro  #头像设置
  pageSize: 10
  lang: en
  highlight: true


# Code Highlight theme
# Available value:
#    default | gray | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# Article theme color
# Available value:
#    random | orange | blue | red | green | black
theme_color: blue


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# CNZZ count
cnzz_siteid: 1260716016

# busuanzi count
# http://busuanzi.ibruce.info/
show_busuanzi_view_counts: true


# donation button
donate:
    enable: false
    message: '如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!'
    wechatImage: css/images/wechat.png
    alipayImage: css/images/alippay.jpg

# post copyright
copyright:
    enable: false


# post edit url, modify your post online for convenience
# If you put your blog on GitHub, it should look like:
# https://github.com/username/blog/edit/master/source/_posts/
post_edit_url:


